# Generated by Django 3.0.5 on 2020-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultrasonic_state', models.CharField(max_length=3)),
                ('face_data', models.TextField(max_length=132000)),
                ('light_reading', models.CharField(max_length=5)),
            ],
        ),
    ]
