# Generated by Django 3.0.7 on 2020-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='face_data',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='light_reading',
            field=models.CharField(max_length=3),
        ),
    ]
